name: "pages build and deployment"
on:
  workflow_dispatch:
  push:
    branches: [ master ]
  schedule:
    # Every 30 min
    - cron:  '*/30 * * * *'


jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build page with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: .
          destination: ./_site
      - name: Archive build output
        run: tar --dereference --hard-dereference --directory _site/ -cvf artifact.tar .
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: github-pages
          path: ./artifact.tar
          if-no-files-found: warn

  deploy:
    needs: build
    permissions:
      contents: 'read'
      pages: 'write'
      id-token: 'write'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/deploy-pages@v1
        id: deployment
        name: Deploy to GitHub Pages
